Repository noclocks/cdn, pull requests merged in 2024-03, with the labels that each got.

#2 [Feature]: Add Frontend Tech Stack SVG Icons
  images/techstack/github.svg
  images/techstack/nodejs.svg
  images/techstack/react.svg
  images/techstack/storybook-s.svg
  images/techstack/storybook.svg
  images/techstack/typescript.svg
  images/techstack/vite.svg
Labels: documentation, feature

#5 Remove duplicate `transparent` in relevant logo filenames (e.g. `noclocks-logo-main-black-transparent-transparent (120x120)`)
  logo/noclocks-logo-main-black-transparent (120x120).png
  logo/noclocks-logo-main-black-transparent (320x320).png
  logo/noclocks-logo-main-black-transparent (500x500).png
Labels: breaking, bug

#6 Remove duplicate transparent in relevant logo filenames (e.g. `noclocks-logo-main-black-transparent-transparent (120x120)`)
  logo/noclocks-logo-main-black-transparent (120x120).png
  logo/noclocks-logo-main-black-transparent (320x320).png
  logo/noclocks-logo-main-black-transparent (500x500).png
Labels: bug, help wanted
